### ISSUE TITLE
Advice on using Python 3?

### ISSUE THREAD

**Issue by michaelaye** [jhamrick/nbflow#7]
Hi!
Thanks for this project, it bridges nicely between using Jupyter and production scripts.
Could you advise or update the installation procedure for using this with a Python 3 project using conda envs? I'm a bit at a loss how I get `nbflow` installed (or 'known'?) if I need to use `pip2` (i.e. a Python 2 env I assume?) to install `nbflow` but then want to work in my Python 3 env?

**Comment by crocha700** [comment]
You can install a [python3 kernel on Jupyter](http://ipython.readthedocs.io/en/stable/install/kernel_install.html?highlight=kernel%20python%202) inside your python2 conda environment.

**Comment by michaelaye** [comment]
Oh DOH! Of course! I'm even doIng that all the time the other way around! Thanks for making me see the forest!
