### ISSUE TITLE
Configure timeout when running nbconvert

### ISSUE THREAD

**Issue by wtbarnes** [jhamrick/nbflow#8]
Currently the `ExecutionPreprocessor.timeout` option when calling nbconvert is [hardcoded at 120 s](https://github.com/jhamrick/nbflow/blob/master/nbflow/scons.py#L11). This is a problem for notebooks that need to run > 2 minutes (e.g. running a small simulation). 

Would there be an easy way to allow the user to set this in the SConstruct file? Or maybe in the notebook itself? I've tried setting this in the notebook with the `% config` magic, but it seems to be overridden by the command line argument in `nbflow/scons.py`.

**Comment by jhamrick** [comment]
Yes, good point, this should definitely be configurable. I'll work on something that makes it so; in the meantime, your best bet is to change it in the source yourself.

**Comment by wtbarnes** [comment]
Thanks! Yes it was a very easy fix just to change the hardcoded value.

Thanks for this great and easy to use tool! I've found it very useful in a couple of projects already.

**Comment by jhamrick** [comment]
Awesome, glad to hear it 😄
